# Generated by Django 5.1.4 on 2024-12-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('intention', models.TextField(blank=True)),
                ('gratitude', models.TextField(blank=True)),
                ('patience', models.TextField(blank=True)),
                ('humility', models.TextField(blank=True)),
                ('awareness', models.TextField(blank=True)),
                ('spiritual_practice', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('personal_improvement', models.TextField(blank=True)),
                ('gratitude_blessings', models.TextField(blank=True)),
                ('accountability', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
